# Generated by Django 6.0.4 on 2026-04-10 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('especialidad', models.CharField(choices=[('clinica_medica', 'Clínica médica'), ('pediatria', 'Pediatría'), ('cardiologia', 'Cardiología'), ('ginecologia', 'Ginecología'), ('traumatologia', 'Traumatología'), ('diagnostico_imagenes', 'Diagnóstico por imágenes'), ('bioquimica', 'Bioquímica'), ('enfermeria', 'Enfermería'), ('farmacia', 'Farmacia'), ('otra', 'Otra')], default='otra', max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
