# Generated by Django 6.0.4 on 2026-04-10 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Obra social',
                'verbose_name_plural': 'Obras sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='obras_sociales.obrasocial')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['obra_social__nombre', 'nombre'],
                'unique_together': {('obra_social', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CoberturaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_afiliado', models.CharField(max_length=50)),
                ('titular', models.CharField(blank=True, max_length=150)),
                ('parentesco', models.CharField(choices=[('titular', 'Titular'), ('conyuge', 'Cónyuge'), ('hijo', 'Hijo/a'), ('otro', 'Otro')], default='titular', max_length=20)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='pacientes.paciente')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coberturas_pacientes', to='obras_sociales.obrasocial')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coberturas_pacientes', to='obras_sociales.plan')),
            ],
            options={
                'verbose_name': 'Cobertura de paciente',
                'verbose_name_plural': 'Coberturas de pacientes',
                'ordering': ['-activa', 'obra_social__nombre'],
            },
        ),
    ]
