# Generated by Django 6.0.4 on 2026-04-10 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0001_initial'),
        ('pacientes', '0002_paciente_provincia'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estudio', models.CharField(max_length=255)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_proceso', 'En proceso'), ('informada', 'Informada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_imagen', to='historia_clinica.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_imagen', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_imagen_emitidas', to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Orden de imagen',
                'verbose_name_plural': 'Órdenes de imágenes',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('practica', models.CharField(max_length=255)),
                ('indicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_proceso', 'En proceso'), ('informada', 'Informada'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_laboratorio', to='historia_clinica.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_laboratorio_emitidas', to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Orden de laboratorio',
                'verbose_name_plural': 'Órdenes de laboratorio',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
