# Generated by Django 6.0.4 on 2026-04-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0002_ordenimagen_ordenlaboratorio'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultado', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('informado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_laboratorio', to='profesionales.profesional')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='historia_clinica.ordenlaboratorio')),
            ],
            options={
                'verbose_name': 'Resultado de laboratorio',
                'verbose_name_plural': 'Resultados de laboratorio',
            },
        ),
        migrations.CreateModel(
            name='ItemResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=50)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('valor_referencia', models.CharField(blank=True, max_length=100)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='historia_clinica.resultadolaboratorio')),
            ],
            options={
                'verbose_name': 'Ítem de resultado',
                'verbose_name_plural': 'Ítems de resultado',
            },
        ),
    ]
